### PR TITLE
Add support for esp-idf v5

### PR DESCRIPTION
**Pull request by jlubawy**
Work in progress PR to add support for esp-idf v5, based on latest release candidate: https://github.com/espressif/esp-idf/releases/tag/v5.0-rc1

I could use some help testing older versions of the esp-idf (v3 and 4) to make sure I didn't introduce breaking changes.

### CODE REVIEW

**Comment by noahp** [comment]
Love it, thank you! I'll test on the 4.x and 3.x versions we support.

**Comment by jlubawy** [comment]
Also here is WIP port for RISC-V (ESP32-C3): https://github.com/jlubawy/memfault-firmware-sdk/pull/1

I'll wait to open a PR until after this one lands, and I have some more time to clean/finish it up.

**Comment by noahp** [comment]
@jlubawy FYI- I've tested this on `v3.3.6`, `v4.4.3`, and `release/v5.0` esp-idf versions. Made a few tweaks to get it working correctly across those versions. We'll refine the patch internally and publish to the SDK- you can find a snapshot of that patch here if you're interested:

https://github.com/memfault/memfault-firmware-sdk/pull/40

**Comment by noahp** [comment]
Hello @jlubawy , FYI I've shipped [v0.36.0](https://github.com/memfault/memfault-firmware-sdk/releases/tag/0.36.0) with this patch, thank you so much for providing it!

**Comment by noahp** [comment]
Closing for now, if there's any issues please feel free to open a Github issue or PR, and thanks again!

**Pull request closed without merging**
